version: '3.6'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports: 
      - 27017:27017
    volumes: 
      - /home/Documentos/Image Mongo Docker:/data/db

